### ISSUE TITLE
[BUG] - Clicking community plugin throws console error

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#143]
### Describe the bug

When you click on the community plugins it throws an error in the console. I don't believe this impacts usability

### How do you reproduce this bug?

1. Navigate to plugins view
2. open dev tools
3. click on any plugin
4. observe error in console

### Expected behavior

No error is thrown

### Screenshots

![image](https://user-images.githubusercontent.com/67948773/233838039-9e53a602-20d2-4b4d-8fd8-a46f6245b57e.png)

### Operating system

Win 10 Pro 10.0.19044

### Community airline

QVirtual

### smartCARS Version

0.8.0.2

### Plugins installed

all except simbrief

### Additional context
When clicking on `simbrief` plugin no error is observed

Error code from screenshot below

```
instrument.ts:124 get-rating-error TypeError: Cannot read properties of null (reading 'id')
    at plugins.jsx:52:50
    at f (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at Zn (asyncToGenerator.js:3:20)
    at o (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:19:12
    at plugins.jsx:64:10
    at plugins.jsx:111:13
    at eu (react-dom.production.min.js:244:332)
    at bl (react-dom.production.min.js:286:111)
    at react-dom.production.min.js:283:409
    at yl (react-dom.production.min.js:281:398)
    at al (react-dom.production.min.js:273:439)
    at zi (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
```

**Comment by GenericNerd** [comment]
I wasn't able to recreate this issue weirdly. Can you provide a video of this happening?

**Comment by Thien42** [comment]
I managed to reproduce the bug, and it will be fixed in the next release
